version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./deployments:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  auth:
    build: .
    depends_on:
      - postgres
    command:
      - "./bin/trimble-auth-server"
    ports:
      - "8080:8080"